package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accounting generated by hbm2java
 */
@Entity
@Table(name="accounting"
    ,catalog="marleo"
)
public class Accounting  implements java.io.Serializable {


     private Integer idAccounting;
     private BigDecimal firstSumGoods;
     private BigDecimal lastSumGoods;
     private Date date;
     private BigDecimal freeMoney;
     private BigDecimal differenceFromSumGoods;

    public Accounting() {
    }

	
    public Accounting(Date date) {
        this.date = date;
    }
    public Accounting(BigDecimal firstSumGoods, BigDecimal lastSumGoods, Date date, BigDecimal freeMoney, BigDecimal differenceFromSumGoods) {
       this.firstSumGoods = firstSumGoods;
       this.lastSumGoods = lastSumGoods;
       this.date = date;
       this.freeMoney = freeMoney;
       this.differenceFromSumGoods = differenceFromSumGoods;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_accounting", unique=true, nullable=false)
    public Integer getIdAccounting() {
        return this.idAccounting;
    }
    
    public void setIdAccounting(Integer idAccounting) {
        this.idAccounting = idAccounting;
    }

    
    @Column(name="firstSumGoods", precision=9)
    public BigDecimal getFirstSumGoods() {
        return this.firstSumGoods;
    }
    
    public void setFirstSumGoods(BigDecimal firstSumGoods) {
        this.firstSumGoods = firstSumGoods;
    }

    
    @Column(name="lastSumGoods", precision=9)
    public BigDecimal getLastSumGoods() {
        return this.lastSumGoods;
    }
    
    public void setLastSumGoods(BigDecimal lastSumGoods) {
        this.lastSumGoods = lastSumGoods;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="freeMoney", precision=9)
    public BigDecimal getFreeMoney() {
        return this.freeMoney;
    }
    
    public void setFreeMoney(BigDecimal freeMoney) {
        this.freeMoney = freeMoney;
    }

    
    @Column(name="differenceFromSumGoods", precision=9)
    public BigDecimal getDifferenceFromSumGoods() {
        return this.differenceFromSumGoods;
    }
    
    public void setDifferenceFromSumGoods(BigDecimal differenceFromSumGoods) {
        this.differenceFromSumGoods = differenceFromSumGoods;
    }




}


