package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArrivalList generated by hbm2java
 */
@Entity
@Table(name = "arrivallist",
         catalog = "marleo"
)
public class ArrivalList implements java.io.Serializable {

    private Long idArrivalList;
    private Arrival arrival;
    private Goods goods;
    private BigDecimal amount;

    public ArrivalList() {
    }

    public ArrivalList(Arrival arrival, Goods goods, BigDecimal amount) {
        this.arrival = arrival;
        this.goods = goods;
        this.amount = amount;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_arrivalList", unique = true, nullable = false)
    public Long getIdArrivalList() {
        return this.idArrivalList;
    }

    public void setIdArrivalList(Long idArrivalList) {
        this.idArrivalList = idArrivalList;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_arrival", nullable = false)
    public Arrival getArrival() {
        return this.arrival;
    }

    public void setArrival(Arrival arrival) {
        this.arrival = arrival;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_goods", nullable = false)
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @Column(name = "amount", nullable = false, precision = 7, scale = 3)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

}
