package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CashOut generated by hbm2java
 */
@Entity
@Table(name = "cash_out",
        catalog = "marleo"
)
public class CashOut implements java.io.Serializable {

    private Integer idCashOut;
    private BigDecimal sumCash;
    private String note;
    private Set caseRecord = new HashSet(0);

    public CashOut() {
    }

    public CashOut(BigDecimal sumCash) {
        this.sumCash = sumCash;
    }

    public CashOut(BigDecimal sumCash, String note, Set caseRecord) {
        this.sumCash = sumCash;
        this.note = note;
        this.caseRecord = caseRecord;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_cashOut", unique = true, nullable = false)
    public Integer getIdCashOut() {
        return this.idCashOut;
    }

    public void setIdCashOut(Integer idCashOut) {
        this.idCashOut = idCashOut;
    }

    @Column(name = "sum_cash", nullable = false, precision = 9)
    public BigDecimal getSumCash() {
        return this.sumCash;
    }

    public void setSumCash(BigDecimal sumCash) {
        this.sumCash = sumCash;
    }

    @Column(name = "note", length = 500)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "caseRecord")
    public Set getCaseRecord() {
        return this.caseRecord;
    }

    public void setCaseRecord(Set caseRecord) {
        this.caseRecord = caseRecord;
    }

}
