package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoryFavorite generated by hbm2java
 */
@Entity
@Table(name = "categoryfavorite",
         catalog = "marleo"
)
public class CategoryFavorite implements java.io.Serializable {

    private Integer idCategoryFavorite;
    private String name;
    private String note;
    private Set categoryFavorite = new HashSet(0);

    public CategoryFavorite() {
    }

    public CategoryFavorite(String name, String note) {
        this.name = name;
        this.note = note;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_categoryFavorite", unique = true, nullable = false)
    public Integer getIdCategoryFavorite() {
        return this.idCategoryFavorite;
    }

    public void setIdCategoryFavorite(Integer idCategoryFavorite) {
        this.idCategoryFavorite = idCategoryFavorite;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "note", nullable = false, length = 100)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryFavorite")
    public Set getCategoryFavorite() {
        return this.categoryFavorite;
    }

    public void setCategoryFavorite(Set categoryFavorite) {
        this.categoryFavorite = categoryFavorite;
    }

}
