package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CheckList generated by hbm2java
 */
@Entity
@Table(name = "checklist",
         catalog = "marleo"
)
public class CheckList implements java.io.Serializable {

    private Long idCheckList;
    private Check check;
    private Goods goods;
    private BigDecimal amount;
    private BigDecimal profit;

    public CheckList() {
    }

    public CheckList(Check check, Goods goods, BigDecimal amount, BigDecimal profit) {
        this.check = check;
        this.goods = goods;
        this.amount = amount;
        this.profit = profit;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_checkList", unique = true, nullable = false)
    public Long getIdCheckList() {
        return this.idCheckList;
    }

    public void setIdCheckList(Long idCheckList) {
        this.idCheckList = idCheckList;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_check", nullable = false)
    public Check getCheck() {
        return this.check;
    }

    public void setCheck(Check check) {
        this.check = check;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_goods", nullable = false)
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @Column(name = "amount", nullable = false, precision = 7, scale = 3)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Column(name = "profit", nullable = false, precision = 7, scale = 3)
    public BigDecimal getProfit() {
        return this.profit;
    }

    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

}
