package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CheckDiscount generated by hbm2java
 */
@Entity
@Table(name = "checklist_newprice",
        catalog = "marleo"
)
public class CheckListNewPrice implements java.io.Serializable {

    private Long idCheckList;
    private CheckList checkList;
    private BigDecimal newPrice;

    public CheckListNewPrice() {
    }

    CheckListNewPrice(CheckList checkList) {
        this.checkList = checkList;
    }

    CheckListNewPrice(CheckList checkList, Discount discount) {
        this.checkList = checkList;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "checkList"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "id_checkList", unique = true, nullable = false)
    public Long getIdCheckList() {
        return this.idCheckList;
    }

    public void setIdCheckList(Long idCheckList) {
        this.idCheckList = idCheckList;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public CheckList getCheckList() {
        return this.checkList;
    }

    public void setCheckList(CheckList checkList) {
        this.checkList = checkList;
    }

    @Column(name = "newPrice", nullable = false, precision = 7, scale = 3)
    public BigDecimal getNewPrice() {
        return newPrice;
    }

    public void setNewPrice(BigDecimal newPrice) {
        this.newPrice = newPrice;
    }
}
