package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Check generated by hbm2java
 */
@Entity
@Table(name = "check",
         catalog = "marleo"
)
public class Check implements java.io.Serializable {

    private Integer idCheck;
    private UserSwing userSwing;
    private BigDecimal sum;
    private BigDecimal money;
    private Date date;
    private String note;
    private CheckDiscount checkDiscount;
    private Set checkLists = new HashSet(0);
    //private Set arrivalLists = new HashSet(0);

    public Check() {
    }

    public Check(UserSwing userSwing) {
        this.userSwing = userSwing;
    }

    public Check(UserSwing userSwing, BigDecimal sum, Date date, String note, CheckDiscount checkDiscount, Set checkLists, BigDecimal money) {
        this.userSwing = userSwing;
        this.sum = sum;
        this.date = date;
        this.note = note;
        this.checkDiscount = checkDiscount;
        this.checkLists = checkLists;
        this.money = money;
        //this.arrivalLists = arrivalLists;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_check", unique = true, nullable = false)
    public Integer getIdCheck() {
        return this.idCheck;
    }

    public void setIdCheck(Integer idCheck) {
        this.idCheck = idCheck;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user", nullable = false)
    public UserSwing getUserSwing() {
        return this.userSwing;
    }

    public void setUserSwing(UserSwing userSwing) {
        this.userSwing = userSwing;
    }

    @Column(name = "sum", precision = 9)
    public BigDecimal getSum() {
        return this.sum;
    }

    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }

    @Column(name = "money", precision = 9)
    public BigDecimal getMoney() {
        return this.money;
    }

    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "note", length = 500)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "check")
    public CheckDiscount getCheckDiscount() {
        return this.checkDiscount;
    }

    public void setCheckDiscount(CheckDiscount checkDiscount) {
        this.checkDiscount = checkDiscount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "check")
    public Set getCheckLists() {
        return this.checkLists;
    }

    public void setCheckLists(Set checkLists) {
        this.checkLists = checkLists;
    }
    
    /*@OneToMany(fetch = FetchType.LAZY, mappedBy = "arrival")
    public Set getArrivalLists() {
    return this.arrivalLists;
    }
    
    public void setArrivalLists(Set arrivalLists) {
    this.arrivalLists = arrivalLists;
    }*/

}
