package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CheckDiscount generated by hbm2java
 */
@Entity
@Table(name = "check_discount",
         catalog = "marleo"
)
public class CheckDiscount implements java.io.Serializable {

    private int idCheck;
    private Check check;
    private Discount discount;

    public CheckDiscount() {
    }

    public CheckDiscount(Check check) {
        this.check = check;
    }

    public CheckDiscount(Check check, Discount discount) {
        this.check = check;
        this.discount = discount;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "check"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "id_check", unique = true, nullable = false)
    public int getIdCheck() {
        return this.idCheck;
    }

    public void setIdCheck(int idCheck) {
        this.idCheck = idCheck;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Check getCheck() {
        return this.check;
    }

    public void setCheck(Check check) {
        this.check = check;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_discount")
    public Discount getDiscount() {
        return this.discount;
    }

    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

}
