package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount",
         catalog = "marleo"
)
public class Discount implements java.io.Serializable {

    private Integer idDiscount;
    private String numcard;
    private String name;
    private String lastname;
    private String phone;
    private String email;
    private Date dateRegister;
    private Date dateUsed;
    private String percent;
    private BigDecimal sumChecks;
    private Set checkDiscounts = new HashSet(0);

    public Discount() {
    }

    public Discount(String numcard, Date dateRegister, Date dateUsed) {
        this.numcard = numcard;
        this.dateRegister = dateRegister;
        this.dateUsed = dateUsed;
    }

    public Discount(String numcard, String name, String lastname, String phone, String email, Date dateRegister, Date dateUsed, String percent, BigDecimal sumChecks, Set checkDiscounts) {
        this.numcard = numcard;
        this.name = name;
        this.lastname = lastname;
        this.phone = phone;
        this.email = email;
        this.dateRegister = dateRegister;
        this.dateUsed = dateUsed;
        this.percent = percent;
        this.sumChecks = sumChecks;
        this.checkDiscounts = checkDiscounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_discount", unique = true, nullable = false)
    public Integer getIdDiscount() {
        return this.idDiscount;
    }

    public void setIdDiscount(Integer idDiscount) {
        this.idDiscount = idDiscount;
    }

    @Column(name = "numcard", nullable = false, length = 50)
    public String getNumcard() {
        return this.numcard;
    }

    public void setNumcard(String numcard) {
        this.numcard = numcard;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "lastname", length = 50)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "phone", length = 50)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_register", nullable = false, length = 19)
    public Date getDateRegister() {
        return this.dateRegister;
    }

    public void setDateRegister(Date dateRegister) {
        this.dateRegister = dateRegister;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_used", nullable = false, length = 19)
    public Date getDateUsed() {
        return this.dateUsed;
    }

    public void setDateUsed(Date dateUsed) {
        this.dateUsed = dateUsed;
    }

    @Column(name = "percent", length = 50)
    public String getPercent() {
        return this.percent;
    }

    public void setPercent(String percent) {
        this.percent = percent;
    }

    @Column(name = "sum_checks", precision = 9)
    public BigDecimal getSumChecks() {
        return this.sumChecks;
    }

    public void setSumChecks(BigDecimal sumChecks) {
        this.sumChecks = sumChecks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "discount")
    public Set getCheckDiscounts() {
        return this.checkDiscounts;
    }

    public void setCheckDiscounts(Set checkDiscounts) {
        this.checkDiscounts = checkDiscounts;
    }

}
