package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsBackup generated by hbm2java
 */
@Entity
@Table(name="goodsbackup"
    ,catalog="marleo"
)
public class GoodsBackup  implements java.io.Serializable {


     private Long idGoods;
     private CategoryGoods categoryGoods;
     private String name;
     private String code;
     private BigDecimal residue;
     private BigDecimal price;
     private BigDecimal priceOpt;
     private Date date;

    public GoodsBackup() {
    }

	
    public GoodsBackup(CategoryGoods categoryGoods, String name, String code) {
        this.categoryGoods = categoryGoods;
        this.name = name;
        this.code = code;
    }
    public GoodsBackup(CategoryGoods categoryGoods, String name, String code, BigDecimal residue, BigDecimal price, BigDecimal priceOpt, Date date) {
       this.categoryGoods = categoryGoods;
       this.name = name;
       this.code = code;
       this.residue = residue;
       this.price = price;
       this.priceOpt = priceOpt;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_goods", unique=true, nullable=false)
    public Long getIdGoods() {
        return this.idGoods;
    }
    
    public void setIdGoods(Long idGoods) {
        this.idGoods = idGoods;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_categoryGoods", nullable=false)
    public CategoryGoods getCategoryGoods() {
        return this.categoryGoods;
    }
    
    public void setCategoryGoods(CategoryGoods categoryGoods) {
        this.categoryGoods = categoryGoods;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="code", nullable=false, length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="residue", precision=7, scale=3)
    public BigDecimal getResidue() {
        return this.residue;
    }
    
    public void setResidue(BigDecimal residue) {
        this.residue = residue;
    }

    
    @Column(name="price", precision=9)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="price_opt", precision=9)
    public BigDecimal getPriceOpt() {
        return this.priceOpt;
    }
    
    public void setPriceOpt(BigDecimal priceOpt) {
        this.priceOpt = priceOpt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


