package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsAccounting generated by hbm2java
 */
@Entity
@Table(name = "goodsaccounting",
         catalog = "marleo"
)
public class GoodsAccounting implements java.io.Serializable {

    private Long idGoodsAccounting;
    private Goods goods;
    private Date date;
    private Boolean checkin;
    private BigDecimal residueNew;
    private BigDecimal residueDiff;

    public GoodsAccounting() {
    }

    public GoodsAccounting(Goods goods) {
        this.goods = goods;
    }

    public GoodsAccounting(Goods goods, Date date, Boolean checkin, BigDecimal residueNew, BigDecimal residueDiff) {
        this.goods = goods;
        this.date = date;
        this.checkin = checkin;
        this.residueNew = residueNew;
        this.residueDiff = residueDiff;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_goodsAccounting", unique = true, nullable = false)
    public Long getIdGoodsAccounting() {
        return this.idGoodsAccounting;
    }

    public void setIdGoodsAccounting(Long idGoodsAccounting) {
        this.idGoodsAccounting = idGoodsAccounting;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_goods", nullable = false)
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "checkin")
    public Boolean getCheckin() {
        return this.checkin;
    }

    public void setCheckin(Boolean checkin) {
        this.checkin = checkin;
    }

    @Column(name = "residue_new", precision = 7, scale = 3)
    public BigDecimal getResidueNew() {
        return this.residueNew;
    }

    public void setResidueNew(BigDecimal residueNew) {
        this.residueNew = residueNew;
    }

    @Column(name = "residue_diff", precision = 7, scale = 3)
    public BigDecimal getResidueDiff() {
        return this.residueDiff;
    }

    public void setResidueDiff(BigDecimal residueDiff) {
        this.residueDiff = residueDiff;
    }

}
