package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReportsAccounting generated by hbm2java
 */
@Entity
@Table(name="reportsaccounting"
    ,catalog="marleo"
)
public class ReportsAccounting  implements java.io.Serializable {


     private Long idReportsAccounting;
     private Goods goods;
     private Date date;
     private BigDecimal residueNew;
     private BigDecimal residueDiff;

    public ReportsAccounting() {
    }

	
    public ReportsAccounting(Goods goods) {
        this.goods = goods;
    }
    public ReportsAccounting(Goods goods, Date date, BigDecimal residueNew, BigDecimal residueDiff) {
       this.goods = goods;
       this.date = date;
       this.residueNew = residueNew;
       this.residueDiff = residueDiff;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_reportsAccounting", unique=true, nullable=false)
    public Long getIdReportsAccounting() {
        return this.idReportsAccounting;
    }
    
    public void setIdReportsAccounting(Long idReportsAccounting) {
        this.idReportsAccounting = idReportsAccounting;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_goods", nullable=false)
    public Goods getGoods() {
        return this.goods;
    }
    
    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="residue_new", precision=7, scale=3)
    public BigDecimal getResidueNew() {
        return this.residueNew;
    }
    
    public void setResidueNew(BigDecimal residueNew) {
        this.residueNew = residueNew;
    }

    
    @Column(name="residue_diff", precision=7, scale=3)
    public BigDecimal getResidueDiff() {
        return this.residueDiff;
    }
    
    public void setResidueDiff(BigDecimal residueDiff) {
        this.residueDiff = residueDiff;
    }




}


