package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Total generated by hbm2java
 */
@Entity
@Table(name = "total",
        catalog = "marleo"
)
public class Total implements java.io.Serializable {

    private Integer idTotal;
    private BigDecimal spare;
    private Date date;
    private BigDecimal sumGoods;
    private BigDecimal profit;
    private UserSwing userSwing;

    public Total() {
    }

    public Total(BigDecimal spare, Date date, BigDecimal sumGoods, UserSwing userSwing) {
        this.spare = spare;
        this.date = date;
        this.sumGoods = sumGoods;
        this.userSwing = userSwing;
    }

    public Total(BigDecimal spare, Date date, BigDecimal sumGoods, BigDecimal profit, long idUser) {
        this.spare = spare;
        this.date = date;
        this.sumGoods = sumGoods;
        this.profit = profit;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_total", unique = true, nullable = false)
    public Integer getIdTotal() {
        return this.idTotal;
    }

    public void setIdTotal(Integer idTotal) {
        this.idTotal = idTotal;
    }

    @Column(name = "proceeds", nullable = false, precision = 9)
    public BigDecimal getSpare() {
        return this.spare;
    }

    public void setSpare(BigDecimal spare) {
        this.spare = spare;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "sumGoods", nullable = false, precision = 9)
    public BigDecimal getSumGoods() {
        return this.sumGoods;
    }

    public void setSumGoods(BigDecimal sumGoods) {
        this.sumGoods = sumGoods;
    }

    @Column(name = "profit", precision = 9)
    public BigDecimal getProfit() {
        return this.profit;
    }

    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user", nullable = false)
    public UserSwing getUserSwing() {
        return this.userSwing;
    }

    public void setUserSwing(UserSwing userSwing) {
        this.userSwing = userSwing;
    }

}
