package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trial generated by hbm2java
 */
@Entity
@Table(name = "trial",
         catalog = "marleo"
)
public class Trial implements java.io.Serializable {

    private Integer idTrial;
    private Date firstdate;
    private Date lastdate;
    private boolean created;
    private String license;

    public Trial() {
    }

    public Trial(Date firstdate, Date lastdate, boolean created) {
        this.firstdate = firstdate;
        this.lastdate = lastdate;
        this.created = created;
    }

    public Trial(Date firstdate, Date lastdate, boolean created, String license) {
        this.firstdate = firstdate;
        this.lastdate = lastdate;
        this.created = created;
        this.license = license;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_trial", unique = true, nullable = false)
    public Integer getIdTrial() {
        return this.idTrial;
    }

    public void setIdTrial(Integer idTrial) {
        this.idTrial = idTrial;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "firstdate", nullable = false, length = 19)
    public Date getFirstdate() {
        return this.firstdate;
    }

    public void setFirstdate(Date firstdate) {
        this.firstdate = firstdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastdate", nullable = false, length = 19)
    public Date getLastdate() {
        return this.lastdate;
    }

    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    @Column(name = "created", nullable = false)
    public boolean isCreated() {
        return this.created;
    }

    public void setCreated(boolean created) {
        this.created = created;
    }

    @Column(name = "license", length = 50)
    public String getLicense() {
        return this.license;
    }

    public void setLicense(String license) {
        this.license = license;
    }

}
