package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name="user_roles"
    ,catalog="marleo"
)
public class UserRoles  implements java.io.Serializable {


     private Integer idRole;
     private String authority;

    public UserRoles() {
    }

    public UserRoles(String authority) {
       this.authority = authority;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRole", unique=true, nullable=false)
    public Integer getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }

    
    @Column(name="authority", nullable=false, length=45)
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


