package ml.model;
// Generated 17.01.2017 17:00:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WriteoffList generated by hbm2java
 */
@Entity
@Table(name = "writeofflist",
         catalog = "marleo"
)
public class WriteoffList implements java.io.Serializable {

    private Long idWriteoffList;
    private Goods goods;
    private Writeoff writeoff;
    private BigDecimal amount;

    public WriteoffList() {
    }

    public WriteoffList(Goods goods, Writeoff writeoff, BigDecimal amount) {
        this.goods = goods;
        this.writeoff = writeoff;
        this.amount = amount;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_writeoffList", unique = true, nullable = false)
    public Long getIdWriteoffList() {
        return this.idWriteoffList;
    }

    public void setIdWriteoffList(Long idWriteoffList) {
        this.idWriteoffList = idWriteoffList;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_goods", nullable = false)
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_writeoff", nullable = false)
    public Writeoff getWriteoff() {
        return this.writeoff;
    }

    public void setWriteoff(Writeoff writeoff) {
        this.writeoff = writeoff;
    }

    @Column(name = "amount", nullable = false, precision = 7, scale = 3)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

}
