package ml.modelLicense;
// Generated 01.07.2017 12:42:23 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Comp generated by hbm2java
 */
@Entity
@Table(name = "comp",
        catalog = "license_ml",
        uniqueConstraints = @UniqueConstraint(columnNames = "mac")
)
public class Comp implements java.io.Serializable {

    private Integer idComp;
    private License license;
    private byte[] mac;
    private byte[] ip;
    private String name;
    private Date dateCreate;
    private String note;
    private String message;

    private Boolean blocking;

    public Comp() {
    }

    public Comp(byte[] mac) {
        this.mac = mac;
    }

    public Comp(License license, byte[] mac, byte[] ip, String name, Date dateCreate, String note, String message, Boolean blocking) {
        this.license = license;
        this.mac = mac;
        this.ip = ip;
        this.name = name;
        this.dateCreate = dateCreate;
        this.note = note;
        this.message = message;
        this.blocking = blocking;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_comp", unique = true, nullable = false)
    public Integer getIdComp() {
        return this.idComp;
    }

    public void setIdComp(Integer idComp) {
        this.idComp = idComp;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_license")
    public License getLicense() {
        return this.license;
    }

    public void setLicense(License license) {
        this.license = license;
    }

    @Column(name = "mac", nullable = false)
    public byte[] getMac() {
        return this.mac;
    }

    public void setMac(byte[] mac) {
        this.mac = mac;
    }

    @Column(name = "ip")
    public byte[] getIp() {
        return this.ip;
    }

    public void setIp(byte[] ip) {
        this.ip = ip;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_create", length = 19)
    public Date getDateCreate() {
        return this.dateCreate;
    }

    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    @Column(name = "note", length = 10000)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }
    
    
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name = "blocking")
    public Boolean getBlocking() {
        return this.blocking;
    }

    public void setBlocking(Boolean blocking) {
        this.blocking = blocking;
    }

}
